# Generated by Django 2.2.4 on 2019-08-24 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citydict',
            name='is_delete',
            field=models.BooleanField(auto_created=True, default=False, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='citydict',
            name='is_disable',
            field=models.BooleanField(auto_created=True, default=False, verbose_name='是否禁用'),
        ),
        migrations.AddField(
            model_name='citydict',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='courseorg',
            name='is_delete',
            field=models.BooleanField(auto_created=True, default=False, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='courseorg',
            name='is_disable',
            field=models.BooleanField(auto_created=True, default=False, verbose_name='是否禁用'),
        ),
        migrations.AddField(
            model_name='courseorg',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_delete',
            field=models.BooleanField(auto_created=True, default=False, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_disable',
            field=models.BooleanField(auto_created=True, default=False, verbose_name='是否禁用'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='citydict',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
    ]
