# Generated by Django 2.2.4 on 2019-09-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citydict',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('pxjg', '培训机构'), ('gr', '个人'), ('gx', '高校')], default='pxjg', max_length=20, verbose_name='机构类别'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='desc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='机构描述'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='org/%Y/%m', verbose_name='封面图'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='tag',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='机构标签'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='points',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='教学特点'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='work_company',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='就职公司'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='work_position',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='公司职位'),
        ),
    ]
