# Generated by Django 2.2.4 on 2019-08-26 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20190824_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citydict',
            old_name='add_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='courseorg',
            old_name='add_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='add_time',
            new_name='create_time',
        ),
    ]
