# Generated by Django 2.2.4 on 2019-09-08 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20190908_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='fav_num',
            new_name='fav_nums',
        ),
    ]
