# Generated by Django 2.2.4 on 2019-08-26 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_auto_20190824_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecomment',
            old_name='add_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='userask',
            old_name='add_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='usercourse',
            old_name='add_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='userfavorite',
            old_name='add_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='usermessage',
            old_name='add_time',
            new_name='create_time',
        ),
    ]
