# Generated by Django 2.2.4 on 2019-08-24 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_delete',
            field=models.BooleanField(auto_created=True, default=False, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_disable',
            field=models.BooleanField(auto_created=True, default=False, verbose_name='是否禁用'),
        ),
        migrations.AddField(
            model_name='course',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='courseresource',
            name='is_delete',
            field=models.BooleanField(auto_created=True, default=False, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='courseresource',
            name='is_disable',
            field=models.BooleanField(auto_created=True, default=False, verbose_name='是否禁用'),
        ),
        migrations.AddField(
            model_name='courseresource',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_delete',
            field=models.BooleanField(auto_created=True, default=False, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_disable',
            field=models.BooleanField(auto_created=True, default=False, verbose_name='是否禁用'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='video',
            name='is_delete',
            field=models.BooleanField(auto_created=True, default=False, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='video',
            name='is_disable',
            field=models.BooleanField(auto_created=True, default=False, verbose_name='是否禁用'),
        ),
        migrations.AddField(
            model_name='video',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(max_length=50, verbose_name='课程类别'),
        ),
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='课程描述'),
        ),
        migrations.AlterField(
            model_name='course',
            name='detail',
            field=models.TextField(default='', max_length=1024, verbose_name='课程详情'),
        ),
    ]
