# Generated by Django 2.2.4 on 2019-08-26 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20190824_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='add_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='courseresource',
            old_name='add_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='add_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='add_time',
            new_name='create_time',
        ),
    ]
