# Generated by Django 2.2.4 on 2019-08-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_deleted',
            field=models.BooleanField(auto_created=True, default=False, verbose_name='是否删除'),
        ),
    ]
