# Generated by Django 2.2.4 on 2019-09-08 10:21

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='image/default.jpg', upload_to=users.models.get_image_path, verbose_name='头像'),
        ),
    ]
