# Generated by Django 2.2.4 on 2019-09-09 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190908_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='nickname',
            new_name='nick_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_disable',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='update_time',
        ),
    ]
