# Generated by Django 2.2.4 on 2019-08-24 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_deleted',
            new_name='is_delete',
        ),
    ]
