# Generated by Django 2.2.4 on 2019-09-09 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190909_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_disable',
            field=models.BooleanField(default=False, verbose_name='是否禁用'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
