# Generated by Django 2.2.4 on 2019-08-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190824_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_disable',
            field=models.BooleanField(auto_created=True, default=False, verbose_name='是否禁用'),
        ),
    ]
