# Generated by Django 2.2.4 on 2019-08-24 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_is_disable'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_delete',
            field=models.BooleanField(auto_created=True, default=False, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='banner',
            name='is_disable',
            field=models.BooleanField(auto_created=True, default=False, verbose_name='是否禁用'),
        ),
        migrations.AddField(
            model_name='banner',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='emailverifyrecord',
            name='is_delete',
            field=models.BooleanField(auto_created=True, default=False, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='emailverifyrecord',
            name='is_disable',
            field=models.BooleanField(auto_created=True, default=False, verbose_name='是否禁用'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间'),
        ),
    ]
